Add by-time and upd workflow
MyAlbum/purge-cache pull request #4
Opened 2023-07-19 09:45 UTC by deemp

- Added an input to delete by `created_at` or `last_accessed_at` time
- Updated workflow to build and then run the `purge-cache` action

Seems to work OK
https://github.com/deemp/purge-cache/actions/runs/5597514115/jobs/10235963061#step:6:19

2023-07-19 13:56 UTC, deemp commented
@Arjan-Zuidema, please, have a look :pray:

2023-07-19 14:25 UTC, Arjan-Zuidema commented on src/index.ts
>        const cacheDate = new Date(cache.last_accessed_at);
You are always checking against `last_accessed_at`, shouldn't that be dynamic based on `created` and `accessed`?

2023-07-19 14:55 UTC, deemp commented on src/index.ts
>        const cacheDate = new Date(cache.last_accessed_at);
Oh, yes. Fixed that

2023-07-26 14:14 UTC, Arjan-Zuidema requested changes

2023-07-26 14:14 UTC, Arjan-Zuidema commented on src/index.ts
>        const cacheDate = new Date(cache.last_accessed_at);
You just changed the logging. Shouldn't it be something like this?

```js
if(created && accessed) {
  // Check created and/or accessed
} else if (created) {
  // Check created
} else if(accessed) {
  // Check accessed
}
```

2023-07-26 17:32 UTC, deemp commented
@Arjan-Zuidema, you probably saw outdated changes

2023-07-26 17:44 UTC, Arjan-Zuidema approved these changes

2023-07-31 06:59 UTC, merged